apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cert-operator
  template:
    metadata:
      labels:
        name: cert-operator
    spec:
      containers:
        - name: cert-operator
          image: quay.io/etsauer/cert-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cert-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "cert-operator"
